### PR TITLE
Save dist folder to support install from github.

### PR DESCRIPTION
**Pull request by sunshineo**
Also this clean up the problem of typescript complain source file not in the rootDir problem
https://github.com/phenomnomnominal/angular-2-local-storage/issues/17

### CODE REVIEW

**Comment by sunshineo** [comment]
Can someone merge this?

**Comment by sunshineo** [comment]
If you don't like the dist folder, you can remove it but you should publish it to npmjs. With the dist folder, the benefit is that it is possible to npm install from git.

**Comment by phenomnomnominal** [comment]
I'm actually on holiday in Thailand, but since you asked so nicely...

**Comment by sunshineo** [comment]
@phenomnomnominal Enjoy Thailand! I was not in an hurry. Just going through all my pull requests and do a weekly ping.

**Comment by phenomnomnominal** [comment]
Published@0.0.20. Sorry for sounding snarky before, just a bit grumpy today 😄! I swear I'm close to actually needing this project, will re-port it to get all the new stuff in angular-local-storage soon.

**Pull request merged**
