### PR TITLE
Update to support Angular 6 and RxJS 6

### LINKED ISSUE #52: rxjs pipe() ?
im using lib in my project 

```
Angular CLI: 6.0.0-rc.2
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/cli: 6.0.0-rc.2
@angular/material: 6.0.0-rc.1
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.5.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.4
@schematics/update: 0.5.4
typescript: 2.7.2
webpack: 4.5.0
```

it was working on 1.7.4 with 5.x rxjs

today i tried to update to cli rc2 and rxjs rx1 and got this 

```

ERROR in ./node_modules/angular-2-local-storage/dist/local-storage.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:...node_modules\angular-2-local-storage\dist'

ERROR in ./node_modules/angular-2-local-storage/dist/local-storage.service.js
Module not found: Error: Can't resolve 'rxjs/Subscriber' in 'C:...node_modules\angular-2-local-storage\dist'

ERROR in ./node_modules/angular-2-local-storage/dist/local-storage.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/share' in 'C:...node_modules\angular-2-local-storage\dist'
```

can you maybe update new rxjs syntax using pipe() thanks

### PR DESCRIPTION
**Pull request by computerwizjared**
Upgrading a project to Angular 6 RC and encountered errors relating to the new breaking RxJS 6 changes, this should fix. Feel free to wait to merge until Angular 6 is fully released, this is just a stop-gap for our project.

Should also resolve #52

### CODE REVIEW

**Comment by colas74** [comment]
this fix is available since " 14 days ago" and still not merged, what  are you waiting for. every times i run "npm i" in my project i need fix it manually. annoying me please accept

**Comment by computerwizjared** [comment]
@colas74 Please respect that the maintainer of this project likely has other commitments, as well as no obligation to keep it maintained.

If you’d like, you may head over to the fork, clone it, then run `npm install` and `npm run build`, then cd into the dist directory and run `npm link .`.

Also keep in mind that I developed my changes based off of an older RC release of angular and have not tested them with the most recent release, so your results may vary. Odds are that the maintainer would like to wait until angular 6 is fully released to merge the pull request.

**Comment by istiti** [comment]
@computerwizjared  afaik current errors aren't related to angular but rxjs (which is v6 released!)  

@colas74 yes npm link could be solution or simply copy service file into your project or you can too use [this one](https://github.com/cyrilletuzi/angular-async-local-storage) Efficient local storage module for Angular apps and PWA: simple API + performance + Observables + validation

**Comment by computerwizjared** [comment]
@istiti My apologies, I didn't realize RxJS 6 came out 3 days ago. I am referencing an RC release in my PR, and haven't tested the stable release with my code yet.

**Comment by elwynelwyn** [comment]
Sorry for the delay - we're super busy over here at the moment!

I've merged the PR but reverted Angular back from v6 RC to the stable v5. The pipeable changes should be enough to get things going in ng6 on their own - please let me know if that is not the case! (you'll have to ignore peer dep warnings for a while longer sorry!).

I also removed the rxjs compat dependency - since the lib uses all pipeable operators now it should not be needed.

Published at 1.0.2

Thanks very much for the PR @computerwizjared!

**Comment by elwynelwyn** [comment]
...aaaand ng6 is out.

I've updated the deps (angular and rxjs) to 6.0.0 and published as a breaking change at v2.0.0

**Comment by colas74** [comment]
Good job, great thanks!

**Pull request merged**
